# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chatty-bunny"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Pelaez"]
  s.date = "2013-08-27"
  s.description = "Experimental RPC on top of Amazon SQS"
  s.email = "pelaez89@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/chatty-bunny.rb",
    "lib/chatty-bunny/base.rb",
    "lib/chatty-bunny/client.rb",
    "lib/chatty-bunny/server.rb",
    "test/helper.rb",
    "test/test_chatty-bunny.rb"
  ]
  s.homepage = "http://github.com/davidpelaez/chatty-bunny"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.0"
  s.summary = "Experimental RPC on top of Amazon SQS"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 4.0.0"])
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 1.15.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
    else
      s.add_dependency(%q<activesupport>, ["~> 4.0.0"])
      s.add_dependency(%q<aws-sdk>, ["~> 1.15.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 4.0.0"])
    s.add_dependency(%q<aws-sdk>, ["~> 1.15.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
  end
end

